# Generated by Django 4.2.2 on 2023-12-06 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='details',
        ),
    ]
